#ifndef __APP_SPEED_H__
#define __APP_SPEED_H__

#define SPEED_EVT_NAME "spid"
#define SPEED_CONTROL_ADJUST_MOTOR 0x01
#define SPEED_CONTROL_OPEN_MOTOR 0x02
#define SPEED_CONTROL_CLOSE_MOTOR 0x04


#define SPEED_CONTROL_EVENT (SPEED_CONTROL_ADJUST_MOTOR | SPEED_CONTROL_OPEN_MOTOR | SPEED_CONTROL_CLOSE_MOTOR)

#endif
