Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('applications', src, depend = [''], CPPPATH = CPPPATH)

group = group + SConscript(os.path.join(cwd, 'aux_modules/', 'SConscript'))

Return('group')
